### PR TITLE
feat: change portal root node instead of subroot node

### PR DESCRIPTION
**Pull request by mihkeleidast**
Related to #2094 - example of what I'd change / expect to happen. Very raw changes, the tests probably fail as well, but hopefully it makes stuff more clear.

@atomiks 

This is a mix of the old (pre #1985) and the current behavior. 

Definitions:
- Root node - the container for multiple floating portals, usually specified on a floating component (i.e. Tooltip, Popover, Modal) level. What was previously `<div id="floating-ui-root">`, currently is `document.body`.
- Subroot node - the container for a single floating portal, appended to the root node. This was essentially a `<React.Fragment>` before, i.e. it did not exist. Right now it is the portal node created for each portal inside of `useFloatingPortalNode`.

Changes:
- This will bring back the default  `<div id="floating-ui-root">` container for all portal subroot nodes. Will clean up the DOM a bit, but would also be useful if the subroot node is disabled on a floating component.
- Specifying either `id` or `node` on a FloatingPortal will only change the root node. The subroot node is a functional requirement, as it has to potentially handle focus events and focus guards, and as such, it should not be customized / merged  / reused for multiple floating elements.
- For a Tooltip-like scenario that does not have to handle any focus elements, it is likely benefitial to provide a way to disable the subroot node. Not sure if this can be derived from some state automatically, or it needs to be a new prop on FloatingPortal. I added some commented out code for this, essentially, if the subroot is disabled, the portal should target the root directly.

### CODE REVIEW

**Comment by atomiks** [comment]
Still confused on this, would be great to have a demo/tests set up that defines the expected behavior for each scenario

**Comment by piecyk** [comment]
@mihkeleidast i think #2182 would kinda allow to have similar structure what you propose #2094

**Comment by mihkeleidast** [comment]
@piecyk I think that PR has the same issues as this one, i.e. it is not immediately clear if/how changing the root node changes the focus handling. I think the current setup, in case the id is not customized, is set up so that the portals are nested in the parent portal if necessary, which probably catches some events. So the question is, how will using a different root node for some components affect this? Also, if you define a custom root for one component, but then render some other floating components inside of that one that do not have a custom root node defined, where should they be rendered? 

I haven't dropped this PR, I just have had to deal with some other work. Still planning to come back to this at some point and work on those questions and a comprehensive test suite. If you're willing to help out with this, it would be appreciated :)

**Comment by piecyk** [comment]
> I think that PR has the same issues as this one, i.e. it is not immediately clear if/how changing the root node changes the focus handling. I think the current setup, in case the id is not customized, is set up so that the portals are nested in the parent portal if necessary, which probably catches some events. So the question is, how will using a different root node for some components affect this? 

It depends one structure, you can push everything under one element `<div id="floating-ui-root" />` but still focus would be handled as now with `usePortalContext` 
 
> Also, if you define a custom root for one component, but then render some other floating components inside of that one that do not have a custom root node defined, where should they be rendered?

It will be rendered like in current impl, inside the floating component, keeping correct order.

**Comment by mihkeleidast** [comment]
> > Also, if you define a custom root for one component, but then render some other floating components inside of that one that do not have a custom root node defined, where should they be rendered?
> 
> It will be rendered like in current impl, inside the floating component, keeping correct order.

This can cause unexpected clipping, can it not? It is an assumption, but if it does, it needs to behave differently, as I wouldn't think clipping would be expected in most cases. Needs testing & validation at least.

**Comment by tuures** [comment]
@mihkeleidast Being able to "sandbox" the app into under a single DOM node (vs `document.body`) would help us a lot. What kind of testing & validation you would be looking for? My suggestion would be to release the feature as "experimental" and gain some experiences using it in practice.

**Comment by atomiks** [comment]
I think that `FloatingPortal` should have a `root` and a `container` prop, where `container` acts like `root` does right now, and `root` is  what `document.body` is now.

**Comment by mihkeleidast** [comment]
> I guess there is that question of ergonomics though, which piecyk's context provider technique solves.
> 
> Assuming you're using the provider globally, everything gets put into a node at the end of `document.body`, so there shouldn't be any clipping.

Do you think the provider solution is better than how `root` worked previously, i.e. by just passing an ID of an element that should exist somewhere? My usecase was to portal a specific component to another root, which could not work with a context solution.

**Comment by piecyk** [comment]
> > I guess there is that question of ergonomics though, which piecyk's context provider technique solves.
> > Assuming you're using the provider globally, everything gets put into a node at the end of `document.body`, so there shouldn't be any clipping.
> 
> Do you think the provider solution is better than how `root` worked previously, i.e. by just passing an ID of an element that should exist somewhere? My usecase was to portal a specific component to another root, which could not work with a context solution.

@mihkeleidast you still can pass ID, that logic is not changed. Basic context provider will make it easy to control the container root without custom wrapper.

**Comment by mihkeleidast** [comment]
> @mihkeleidast you still can pass ID, that logic is not changed. Basic context provider will make it easy to control the container root without custom wrapper.

Generally floating-ui always requires custom component wrappers anyway, but gotcha. Maybe the provider should be more agnostic to potentially allow other options to be globally configured as well, not just the default portal root id? Not sure if there are such needs today, but would at least future-proof it a bit, I think.

**Comment by piecyk** [comment]
> Maybe the provider should be more agnostic to potentially allow other options to be globally configured as well, not just the default portal root id? Not sure if there are such needs today, but would at least future-proof it a bit, I think.

Hmm hard to say, would keep it simple for now, what do you think @atomiks?

**Comment by atomiks** [comment]
Starting simple seems good to me. If use cases emerge we can work from it.

**Comment by piecyk** [comment]
> Starting simple seems good to me. If use cases emerge we can work from it.

Great, let me know if anything is missing here https://github.com/floating-ui/floating-ui/pull/2182

**Comment by atomiks** [comment]
I think we're pretty close to merging https://github.com/floating-ui/floating-ui/pull/2182 instead, so closing this one

**Pull request closed without merging**
