### PR TITLE
feat: add middleware to adjust y-coordinate on Android

### LINKED ISSUE #2904: [React-native] Android does not adjust based on reference's y-cordinate
**Describe the bug**
With react-native android, floating element does not correctly adjust for height of views before the reference view. Even with `collapsable={false}`, as pointed out in the docs.

**To Reproduce**

https://snack.expo.dev/@mookiies/floating-scollview Snack takes basic example from docs, and adds a 100 tall view as first child.

Compare Android vs iOS/web behavior

**Expected behavior** 
Behavior matches on all platforms, and Android floating view is updated to adjust based on reference's layout height. 

Screenshot 2024-05-16 at 11 41 13 AM
Screenshot 2024-05-16 at 11 40 53 AM
Screenshot 2024-05-16 at 11 40 24 AM

**Context:**

Tested repro on Expo 51 (RN 0.74, containing new Yoga) and Expo 50 (RN 0.73)

**Additional context**

It seems that, despite `onLayout` producing a correct measurement for the reference view, the android floating styles does not take this into account.

```
sdk_gphone_x86_64:(android onLayout) x:0, y:100.19047546386719, w:411.4285583496094, h:19.428571701049805
sdk_gphone_x86_64:(android floatingStyles) {"position":"absolute","left":180.5714225769043,"top":19.428571701049805}

iPhone 15 Pro:(ios onLayout) x:0, y:100, w:393, h:17
iPhone 15 Pro:(ios floatingStyles) {"position":"absolute","left":170.6666660308838,"top":117}

Firefox:(web onLayout) x:0, y:100, w:484, h:17
Firefox:(web floatingStyles) {"position":"absolute","left":216,"top":117}
```

### PR DESCRIPTION
**Pull request by sarabjit20s**
### Description
This PR introduces a new middleware `adjustYCoordOnAndroid` to address an issue(#2904) with the y coordinate offset on Android devices when sameScrollView is set to false. On Android, the y coordinate currently ignores the status bar height, causing positioning issues in certain layouts. This middleware adjusts the y coordinate by adding the StatusBar height when running on Android.

### Changes Made

- **Added `adjustYCoordOnAndroid` middleware:** This middleware checks if the platform is Android and, if so, adds StatusBar.currentHeight to the y coordinate, ensuring consistent positioning.

### Testing

- Tested on Android devices and verified that the y coordinate aligns correctly with the status bar.
- Confirmed that the middleware has no impact on iOS behavior, ensuring cross-platform consistency.

### Related Issues
Resolves #2904

### CODE REVIEW

**Comment by FezVrasta** [comment]
I don't think this should be a middleware. The core logic should be changed to address this

**Comment by atomiks** [comment]
Yep agree with @FezVrasta, you should be able to add this inside `createPlatform`

**Comment by sarabjit20s** [comment]
> Yep agree with @FezVrasta, you should be able to add this inside `createPlatform`

ok

**Comment by sarabjit20s** [comment]
> Yep agree with @FezVrasta, you should be able to add this inside `createPlatform`

What do you guys think about this implementation: 
### Changes Made In

1. `reference[method] ` callback
2. `getClippingRect` method

```
import type {Platform, VirtualElement} from '@floating-ui/core';
import {Dimensions, Platform as RNPlatform, StatusBar} from 'react-native';
import type {View} from 'react-native';

const ORIGIN = {x: 0, y: 0};

const isAndroid = RNPlatform.OS === 'android';

function isView(reference: View | VirtualElement): reference is View {
  return 'measure' in reference;
}

export const createPlatform = ({
  offsetParent,
  sameScrollView = true,
  scrollOffsets = ORIGIN,
}: {
  offsetParent: View;
  sameScrollView: boolean;
  scrollOffsets: {
    x: number;
    y: number;
  };
}): Platform => ({
  getElementRects({
    reference,
    floating,
  }: {
    reference: View | VirtualElement;
    floating: View;
  }) {
    return new Promise((resolve) => {
      const onMeasure = (offsetX = 0, offsetY = 0) => {
        floating.measure(
          (x: number, y: number, width: number, height: number) => {
            const floatingRect = {width, height, ...ORIGIN};
            const method = sameScrollView ? 'measure' : 'measureInWindow';

            if (isView(reference)) {
              reference[method](
                (x: number, y: number, width: number, height: number) => {
                  y = isAndroid && !sameScrollView ? y + StatusBar.currentHeight : y;
                  const referenceRect = {
                    width,
                    height,
                    x: x - offsetX,
                    y: y - offsetY,
                  };

                  resolve({reference: referenceRect, floating: floatingRect});
                },
              );
            } else {
              const boundingRect = reference.getBoundingClientRect();
              const referenceRect = {
                width: boundingRect.width,
                height: boundingRect.height,
                x: boundingRect.x - offsetX,
                y: boundingRect.y - offsetY,
              };

              resolve({reference: referenceRect, floating: floatingRect});
            }
          },
        );
      };

      if (offsetParent) {
        offsetParent.measure(onMeasure);
      } else {
        onMeasure();
      }
    });
  },
  getClippingRect() {
    const {width: windowWidth, height: windowHeight} = Dimensions.get('window');
    const {height: screenHeight} = Dimensions.get('screen');
    const statusBarHeight = StatusBar.currentHeight || 0;
    // on iOS: screenHeight = windowHeight
    // on Android: screenHeight = windowHeight + statusBarHeight + navigationBarHeight
    const navigationBarHeight = isAndroid
      ? screenHeight - windowHeight - statusBarHeight
      : 0;
    return Promise.resolve({
      width: windowWidth,
      height: screenHeight - navigationBarHeight,
      ...(sameScrollView ? scrollOffsets : ORIGIN),
    });
  },
  convertOffsetParentRelativeRectToViewportRelativeRect({rect}) {
    return new Promise((resolve) => {
      const onMeasure = (offsetX = 0, offsetY = 0) => {
        resolve({...rect, x: rect.x + offsetX, y: rect.y + offsetY});
      };

      if (offsetParent) {
        offsetParent.measure(onMeasure);
      } else {
        onMeasure();
      }
    });
  },
  getDimensions: (element) =>
    new Promise((resolve) =>
      element.measure((x: number, y: number, width: number, height: number) =>
        resolve({width, height}),
      ),
    ),
});
```

**Comment by FezVrasta** [comment]
@sarabjit20s could you update the PR with the proposed changes? It will be easier to review them.

**Review by FezVrasta — APPROVED** [review]
LGTM but I haven't tested it, I don't have a react-native environment setup to test this out. If you could provide a few videos of the lib working on both iOS and Android it would be helpful.

**Comment by sarabjit20s** [comment]
> LGTM but I haven't tested it, I don't have a react-native environment setup to test this out. If you could provide a few videos of the lib working on both iOS and Android it would be helpful.


https://github.com/user-attachments/assets/175710e4-d964-408b-b8ff-6ec2adb675c0


https://github.com/user-attachments/assets/8fe85e17-1b22-46f7-9bf8-6b59650e2e81

**Pull request merged**
