### PR TITLE
fix(useTypeahead): allow type ahead when currentTarget contains target

### LINKED ISSUE #2172: [React] useTypeahead with different currentTarget
Having combobox with structure below, would like to enable useTypeahead when searchable is disabled, 

```jsx
<div {...getReferenceProps({ className: styles.wrapper })>
  <Input readOnly={!searchable}>
  <div>clear<div>
  <div>toggle menu<div>
</div>
```
Issue is here https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useTypeahead.ts#L87-L96 basic activeElement is input, but currentTarget is the wrapper.

As wrapper will have role `combox`, when adding it to list of `target.closest` should work as expected https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useTypeahead.ts#L91

### PR DESCRIPTION
**Pull request by piecyk**
fixes #2172

### CODE REVIEW

**Comment by atomiks** [comment]
Doesn't that break this comment requirement?

```js
      // Correctly scope nested non-portalled floating elements. Since the nested
      // floating element is inside of the another, we find the closest role
      // that indicates the floating element scope.
```

If so, maybe a callback filter to let the user decide whether it should work is best?

**Comment by piecyk** [comment]
> Doesn't that break this comment requirement?
> 
> ```js
>       // Correctly scope nested non-portalled floating elements. Since the nested
>       // floating element is inside of the another, we find the closest role
>       // that indicates the floating element scope.
> ```
> 
> If so, maybe a callback filter to let the user decide whether it should work is best?

hmm good questions. This contains should only be checked in context of reference, current code works because assumes that reference is the active element when validating useTypeahead, otherwise we are in floating elements.

**Comment by atomiks** [comment]
Thanks! Can you add a test in `useTypeahead.test.tsx`?

**Comment by piecyk** [comment]
> Thanks! Can you add a test in `useTypeahead.test.tsx`?

@atomiks added.

**Comment by atomiks** [comment]
Thanks!

**Pull request merged**
