### PR TITLE
Add Linux screenshots for Playwright tests

### PR DESCRIPTION
**Pull request by megawebmaster**
As I began working on improving my PR I needed base images for comparison in functional tests. As the repo is missing Linux images I decided it's the right thing to contribute them :wink:

### CODE REVIEW

**Comment by atomiks** [comment]
Linux had an unexplainable flaky test for some reason so I switched to macOS which is a lot less so, I think the `Update Visual Snapshots` action may just need to be updated for you?

**Comment by megawebmaster** [comment]
@atomiks - everything worked well for me as long as I generate images using `npm run test:functional:update` and then verify them by `npm run test:functional`. Do you want me to add linux testing to the GH Action too?

**Comment by atomiks** [comment]
@megawebmaster There's no need for the Linux screenshots now as the macOS screenshots cover the same functionality. So feel free to leave them out of your PR

**Comment by megawebmaster** [comment]
@atomiks - the problem is that I cannot verify on my machine if tests should pass or I broke something. I don't own a MacBook (or any other Apple system) to check against `master` branch. What is more - I can't generate proper images in my next PR (as they will miss images anyway). How do you want me to approach that?

**Comment by atomiks** [comment]
In your fork, click `Actions` > `Update Visual Snapshots` > Choose your branch. The GitHub bot will commit the macOS screenshots to your branch for you

**Pull request closed without merging**
