### PR TITLE
fix(dom): cross-document/iframe support

### PR DESCRIPTION
**Pull request by atomiks**
This takes into account the `x` and `y` offset of an `iframe` and its scale.

Fixes https://github.com/floating-ui/floating-ui/issues/1594
Fixes https://github.com/floating-ui/floating-ui/issues/1711
Fixes https://github.com/floating-ui/floating-ui/issues/1869
Fixes https://github.com/floating-ui/floating-ui/issues/1870

- [x] Visual snapshots

Any issues? Added nesting support, tests for both inside vs. outside + nesting. Seems to work with `limitShift` as well.

@mishushakov
@talldan
@ciampo 
@seahindeniz

### CODE REVIEW

**Comment by ciampo** [comment]
Hey @atomiks, is this fix already included in the latest version of the `@floating-ui/dom` package (i.e `1.1.0`) ?

I gave it a quick look and it doesn't seem to fix the issues that we were trying to fix in https://github.com/WordPress/gutenberg/

**Comment by atomiks** [comment]
Hey yeah it's in `1.1.0`. Can you take a look at the iframe visual tests and see if it's missing a particular case which causes it to not work?

**Comment by ciampo** [comment]
I'm not quite sure — I gave a quick look at the visual tests and they seem comprehensive.

I've opened a draft PR https://github.com/WordPress/gutenberg/pull/46845 to hopefully help debugging what's going on.

Would be open to having a chat so that we can more easily discuss the issue at hand? If so, you can find me on the [Make WordPress slack](https://make.wordpress.org/chat/) as `mciampini` — I'd love to collaborate and get to the bottom of the cross-document support feature!

**Comment by atomiks** [comment]
@ciampo yes sure, I'll join soon

**Comment by ciampo** [comment]
Awesome! Cc'ing @jsnajdr who is potentially interested in collaborating on this too.

**Pull request merged**
