### PR TITLE
ancestorResize uses ResizeObserver when available

### PR DESCRIPTION
**Pull request by michaelglass**
just dropping this here to see if it's a welcome addition / curious why it's not implemented this way.

I had to add this logic to my own project to get my floaties to follow their target element correctly.

Will flesh it out (changeset? tests?) if the change is desired. ❤️

### CODE REVIEW

**Comment by atomiks** [comment]
I think using `ResizeObserver` for ancestor resizing is now unnecessary after the `layoutShift` option got introduced? `ResizeObserver` can throw annoying console errors due to loops, so it'd be good to avoid it whenever possible.

**Comment by michaelglass** [comment]
[here's a reproduction of my issue](https://codesandbox.io/p/sandbox/lingering-smoke-ng982v?workspaceId=d2f24a17-1b82-4153-b984-f60885a19f9f&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyo52rvu00073b6iptjz9pfb%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyo52rvu00033b6ity77kixo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyo52rvu00043b6invfdjqoc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyo52rvu00063b6iljndcj9o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyo52rvu00033b6ity77kixo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyo52rvu00023b6ic8l8k1ji%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A17%257D%255D%257D%252C%257B%2522id%2522%253A%2522clyo68sgw00023b6i4nvdo71f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyo52rvu00033b6ity77kixo%2522%252C%2522activeTabId%2522%253A%2522clyo68sgw00023b6i4nvdo71f%2522%257D%252C%2522clyo52rvu00063b6iljndcj9o%2522%253A%257B%2522id%2522%253A%2522clyo52rvu00063b6iljndcj9o%2522%252C%2522activeTabId%2522%253A%2522clyo53qkv001h3b6ievvvvxqf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyo52rvu00053b6i1wrk2krk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clyo531ms000a3b6iu23mt7po%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clyo53qkv001h3b6ievvvvxqf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clyo52rvu00043b6invfdjqoc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyo52rvu00043b6invfdjqoc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by atomiks** [comment]
Oh ok yeah that's an unhandled edge case that `layoutShift` doesn't solve (since the reference isn't moving). Is there a reason the floating element needs to be inside a `position: relative` container?

**Comment by michaelglass** [comment]
@atomiks thanks for your feedback. In retrospect: I don't think it does need to be in a position:* container.

**Pull request closed without merging**
