### PR TITLE
new package for SolidJS

### PR DESCRIPTION
**Pull request by madaxen86**
Rewrote all React components and hooks to SolidJS.
Also rewrote all tests -- all pass
Added build command to top level package.json
To do:
- add a changeset
- docs? - as Solid does not have a VDOM and doesn't rerender components - using the hooks and components is very different compared to React.

### CODE REVIEW

**Comment by atomiks** [comment]
Wow this looks like a lot of work, nicely done! 

I always wanted to have a vanilla core that contains most of the logic, which can then be wrapped by frameworks. This would prevent a large portion of duplication. I'm not sure how feasible or practical this is though — of course, the positioning logic achieves this already, but interactions are way more specific and finicky (e.g. React event system and portals).

I understand it's a ton of work to document everything. Even the React docs are partially incomplete as it was still in v0. Ideally, I need to clean up some of the APIs and get it ready for v1, which means this would need to also follow suit. If this were to be merged, how available are you regarding maintenance? Since I don't have experience with SolidJS, I won't be able to contribute or fix issues. If maintenance is an issue, then a third-party package might be best here.

Thank you for the contribution here!

**Comment by madaxen86** [comment]
> Wow this looks like a lot of work, nicely done!
> 
> I always wanted to have a vanilla core that contains most of the logic, which can then be wrapped by frameworks. This would prevent a large portion of duplication. I'm not sure how feasible or practical this is though — of course, the positioning logic achieves this already, but interactions are way more specific and finicky (e.g. React event system and portals).
> 
> I understand it's a ton of work to document everything. Even the React docs are partially incomplete as it was still in v0. Ideally, I need to clean up some of the APIs and get it ready for v1, which means this would need to also follow suit. If this were to be merged, how available are you regarding maintenance? Since I don't have experience with SolidJS, I won't be able to contribute or fix issues. If maintenance is an issue, then a third-party package might be best here.
> 
> Thank you for the contribution here!

Hey Atomiks,
yeah was a lot of work and helped me to get to understand the differences between React (which I am using usually) and Solid. 
As I am just coding for fun, I'll sure find time here and then for maintenance and also provide proper documentation. 
Regarding the docs, we'd then need to find a good concept how to integrate other frameworks.
But  stumbled over a little problem. On my machine I used PNPM and everything is woking fine. Now that I've seen that the PR failed test I switched to NPM on my machine and some tests are failing, because Vitest somehow uses multiple instances of Solid for whatever reason. Long story short, after a day if trying everything to fix it, I couldn't figure out a way with NPM. How much of a hustle would it be to switch to PNPM?

**Comment by madaxen86** [comment]
Hey @atomiks ,
I have completed the docs for Solid.
Linting and type checking failed because of 'npm ERR! network This is a problem related to network connectivity.' !?
I hope you can merge this PR quickly. I then have to create and add links to codesandboxes. But first the package has to be published before I can create them.

**Comment by atomiks** [comment]
Hey @madaxen86, I **really** appreciate the work you've put into this, I think it's excellent!

However, I don't think we have the bandwidth to maintain a Solid package "officially". It's a lot of work to maintain the React one as it is already, and it's not even close to being feature-complete, so trying to ensure the Solid one is in sync simultaneously with new features is just too much work 😢 

You're totally welcome to publish this as a third party library and maintain it in your own repository. I hope that this is a suitable option for you - thank you!

**Comment by madaxen86** [comment]
I don't intend to, because I don't want to maintain my own documentation page etc.
For me this was a project to get deeper into Solid.
I can highly recommend to use kobalte.dev 
It provides primitives and unstyled components which already have all the setup done to create a great component library. E.g. SolidUi is build on top of it.

**Pull request closed without merging**
