### PR TITLE
fix: replace includes with indexOf to support old browser

### PR DESCRIPTION
**Pull request by guaqiu5**
replace includes with indexOf to support old browser

### CODE REVIEW

**Comment by FezVrasta** [comment]
We don't support older browsers, making this change wouldn't make Floating UI compatible.

**Comment by guaqiu5** [comment]
> We don't support older browsers, making this change wouldn't make Floating UI compatible.
 but it will cause the js error rate of the website to increase😫

**Comment by FezVrasta** [comment]
The library is not going to work nonetheless, having an error makes that even clearer. We suggest to include polyfills for unsupported functionalities when deemed appropriate

**Comment by guaqiu5** [comment]
image
This is the jserror stack information for users of low version browsers
Low version of the browser errors occurred in case of Array some & includes methods, my guess is that the "packages/utils/dom/SRC/index" isContainingBlock function cause it.

**Comment by piecyk** [comment]
@guaqiu5 something is not right, as here we see import from core-js, basic you can configure what browser do you suport and it will automatically pick the polyfills

**Pull request closed without merging**
