### PR TITLE
Does not throw when component type reference or floating renders nothing

### LINKED ISSUE #2691: Vue HeadlessUI + FloatingUI: Failed to execute 'getComputedStyle' on 'Window'
**Describe the bug** 

When using Vue version, I get the following errors:

```
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at getComputedStyle (floating-ui.dom.umd.js:87:31)
    at isOverflowElement (floating-ui.dom.umd.js:55:9)
    at getOverflowAncestors (floating-ui.dom.umd.js:138:57)
    at autoUpdate (floating-ui.dom.umd.js:655:121)
    at attach (floating-ui.vue.umd.js:141:39)
    at callWithErrorHandling (vue.esm-browser.js:1663:22)
    at callWithAsyncErrorHandling (vue.esm-browser.js:1673:21)
    at job (vue.esm-browser.js:3085:17)
    at resetScheduling (vue.esm-browser.js:594:38)
    at triggerEffects (vue.esm-browser.js:638:5)
```

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'defaultView')
    at getDPR (floating-ui.vue.umd.js:38:39)
    at roundByDPR (floating-ui.vue.umd.js:43:17)
    at eval (floating-ui.vue.umd.js:93:20)
    at ReactiveEffect.eval [as fn] (vue.esm-browser.js:1257:48)
    at ReactiveEffect.run (vue.esm-browser.js:507:25)
    at get value [as value] (vue.esm-browser.js:1266:67)
    at triggerComputed (vue.esm-browser.js:528:21)
    at get dirty [as dirty] (vue.esm-browser.js:481:21)
    at instance.update (vue.esm-browser.js:6694:24)
    at callWithErrorHandling (vue.esm-browser.js:1663:36)
```

**To Reproduce**

https://stackblitz.com/edit/vue-tzedys?file=src%2Fcomponents%2FHelloWorld.vue

1. Run the project
2. Inspect console errors

**Expected behavior** 

Project should run without issues.

**Screenshots** 

image

**Context:**

- OS: iOS
- Browser chrome
- Version 120

**Additional context**

I am using custom components for both reference and floating. Maybe that is the issue? Looking at the code, it seems like computed proprety returning floating element {el: _, $el: _} is passed to a function as HTML element?

### PR DESCRIPTION
**Pull request by lozinsky**
Fixes #2691

### CODE REVIEW

**Comment by Muratovnik** [comment]
this pr twhrow error when floating reference wapped in <Transition> component

**Comment by lozinsky** [comment]
@Muratovnik could you please provide a code snippet? What version of Vue are you using?

**Comment by Muratovnik** [comment]
I think, this problem not related to Transition. Floating UI throws error, because checking code pass undefined value. I tried to replace 
```typescript
if (isComponentPublicInstance(target)) {
    const element = target.$el as Exclude<MaybeElement<T>, ComponentPublicInstance>;

    return isNode(element) && getNodeName(element) === '#comment' ? null : element;
  }

  return target as Exclude<MaybeElement<T>, ComponentPublicInstance>;
```
to 
```typescript
return target?.$el || target || null;
```
and its work fine and not throw error with undefined element.

Sorry, i can't provide code snipped

**Comment by lozinsky** [comment]
Could you provide a minimal example to reproduce the issue in sandbox?

https://codesandbox.io/p/sandbox/floating-ui-vue-tooltip-8718xk

**Pull request merged**
