### PR TITLE
fix: `detectOverflow` should use state rect

### PR DESCRIPTION
**Pull request by AlexStrNik**
Second try of #1326

### CODE REVIEW

**Comment by FezVrasta** [comment]
Tests are still failing ☹️

**Comment by AlexStrNik** [comment]
Yeah, I'm trying to fix them now

**Comment by FezVrasta** [comment]
@AlexStrNik did you find time to look into this?

**Comment by AlexStrNik** [comment]
Sorry, not yet... I have some busy months right now

**Pull request closed without merging**
