### PR TITLE
fix: update getOffsetParent#getContainingBlock to avoid shadow roots when traversing ancestors

### PR DESCRIPTION
**Pull request by jcfranco**
#1815 identified the need to avoid shadow roots while traversing ancestors when looking for the containing block. This adds the missing check left out from https://github.com/floating-ui/floating-ui/pull/1535:

> I only modified getOffsetParent to use the host if the starting element's parent is a shadow root, **but this may also be needed for subsequent parent node lookups**.

@atomiks I did not find any existing shadow DOM tests, so please let me know how you'd like me to add coverage for this.

### CODE REVIEW

**Comment by atomiks** [comment]
@jcfranco thanks for the PR. I think shadow DOM tests would be great, Popper had these but transition to React/Parcel tests lost them.

**Comment by jcfranco** [comment]
@atomiks I had to slightly sidestep React to set up the custom element scenarios, but this now has shadow DOM tests. May the React gods have mercy on my soul.

**Comment by atomiks** [comment]
Are these images meant to have no floating element visible? 

https://github.com/floating-ui/floating-ui/blob/0d6d83323c658179d94d3c6f4de944d63f4150cf/packages/dom/test/functional/shadow-dom.test.ts-snapshots/direct-host-child-top-fixed-with-transform-darwin.png

**Comment by jcfranco** [comment]
Yikes, they are most definitely not. Apologies.

The issue was that the last click in the functional test did not trigger repositioning in the custom element. This is now fixed and the accompanying screenshots are now up to date.

**Comment by jcfranco** [comment]
FWIW, the following shows the combination of options that this PR fixes:

### before
Screen Shot 2022-08-03 at 12 52 07 AM

### after
Screen Shot 2022-08-03 at 12 52 33 AM

**Comment by atomiks** [comment]
Thank you!

**Comment by atomiks** [comment]
By any chance, do you have an idea of how to fix https://github.com/floating-ui/floating-ui/issues/1729 as well? It seems somewhat important. I think we have to avoid `.offsetParent` entirely for the `getTrueOffsetParent` function.

**Comment by jcfranco** [comment]
I haven’t spent time on that issue, TBH. Would it be reasonable to fix it by using the old `offsetParent` behavior polyfill you found while a better approach is in the works? Seems like it’d be worth the extra bytes for consistent browser behavior.

**Pull request merged**
