### PR TITLE
perf(core): add pure annotation for allPlacements const

### PR DESCRIPTION
**Pull request by webistomin**
I just discovered the library is not fully tree-shakeable for some reason, so I added a `/* #__PURE__ */` comment.

### CODE REVIEW

**Comment by atomiks** [comment]
I think there's a Babel plugin that does this for us automatically? Which parts weren't tree-shakeable? I know CRA has problems but Parcel/Rollup/etc. work 🧐

**Comment by webistomin** [comment]
I use [agadoo](https://github.com/Rich-Harris/agadoo) for such purposes. As far as I know it uses rollup under the hood. 

I have never used this babel plugin, but I think it should help.

Before:

```
const basePlacements = ['top', 'right', 'bottom', 'left'];
const allPlacements = basePlacements.reduce((acc, basePlacement) => acc.concat(basePlacement, basePlacement + "-start", basePlacement + "-end"), []);

Failed to tree-shake dist\floating-ui.core.esm.js
```

After:

```
Success! dist\floating-ui.core.esm.js is fully tree-shakeable
```

**Comment by webistomin** [comment]
The plugin also adds annotation in the same place as me.😉

 Is it better to use Babel?

**Comment by atomiks** [comment]
Having a plugin do it automatically for us is better, since we might add more code that needs it 👍

**Comment by webistomin** [comment]
Done

**Pull request merged**
