### PR TITLE
fix(getClippingRect): fix incorrect clipping rect calculation with fixed ancestors

### PR DESCRIPTION
**Pull request by atomiks**
Fixes https://github.com/floating-ui/floating-ui/issues/2288

@leandro-fenoglio-ca @sallerli1 @jcfranco  can you test this change on the scenario(s) that have been failing for you to see if they are fixed?

### CODE REVIEW

**Comment by jcfranco** [comment]
@atomiks Nested floating-ui elements are no longer hidden, but positioning is still off.

test-floating-ui-hidden-modifier-tweaks

**Comment by atomiks** [comment]
@jcfranco can you post a sandbox with that structure shown?

**Comment by jcfranco** [comment]
Sure thing. Here is the original use case reported to us: https://codepen.io/cont-kolomeets/pen/yLERQPx?editors=1000

**Comment by jcfranco** [comment]
Gotcha. I'll work on creating an isolated repro case.

**Comment by leandro-fenoglio-ca** [comment]
> Fixes #2288
> 
> @leandro-fenoglio-ca @sallerli1 @jcfranco can you test this change on the scenario(s) that have been failing for you to see if they are fixed?

@atomiks , thank you very much for the support. I tested your solution here and it solved the problem that was happening.

One question, after reviewing and approving this solution, will it be applied to `popperjs` as well?

**Comment by atomiks** [comment]
No problem

> One question, after reviewing and approving this solution, will it be applied to popperjs as well?

If you want to contribute it sure :) I'm only working on Floating UI, but Popper can receive fixes from external contributions.

**Comment by sallerli1** [comment]
@atomiks  I built and tested in our codes, the issue is fixed, thanks a lot for your support!

**Comment by atomiks** [comment]
I'm going to merge this since it fixes the linked issue's problem, but if you find time to make a minimal repro @jcfranco feel free to open a new issue

**Pull request merged**
